version: "3"
services:
  mopidy:
    build: .
    image: mopidy
    container_name: mopidy
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - /opt/mopidy/mopidy.conf:/var/lib/mopidy/mopidy.conf
      - /media:/media
    devices:
      - "/dev/snd:/dev/snd"
