FROM  arm32v7/debian:buster-slim

LABEL maintainer="hoboristi" \
      dockerfile-version="1.0" \
      description="Docker image for mopidy"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG   DEBIAN_FRONTEND=noninteractive

USER  root

RUN   mkdir -p /usr/share/man/man1

COPY  qemu-arm-static /usr/bin/qemu-arm-static

RUN   apt-get update \
      && apt-get install -y wget gnupg gnupg2 curl apt-utils \
      && mkdir -p /usr/local/share/keyrings \
      && wget -q -O /usr/local/share/keyrings/mopidy-archive-keyring.gpg \
  https://apt.mopidy.com/mopidy.gpg \
      && wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list \
      && apt-get update \
      && apt-get install -y \
                        mopidy \
                        mopidy-mpd \
                        mopidy-local \
                        mopidy-dleyna \
                        python3 \
                        python3-pip \
                        python-crypto \
                        python-setuptools \
                        python-alsaaudio \
                        sudo \
                        gstreamer1.0-alsa \
                        gstreamer1.0-libav 

# RUN   && apt-get clean \
#     && rm -rf /var/lib/apt/lists/* 
RUN   apt-get install -y gcc-arm-none-eabi
RUN   python3 -m pip install \
                        wheel \
                        pyalsaaudio \
                        setuptools
RUN   python3 -m pip install \
                        Mopidy-Iris \
                        Mopidy-Tidal \
                        Mopidy-YouTube

ADD mopidy.conf /etc/mopidy.conf

# RUN   echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers

ADD docker-entrypoint.sh /docker-entrypoint.sh
# COPY  docker-entrypoint.sh /

RUN chown root:audio -R /var/lib/mopidy \
    && chown root:audio /docker-entrypoint.sh

ADD localscan /usr/bin/localscan
RUN chmod +x /usr/bin/localscan

VOLUME /var/lib/mopidy

EXPOSE 6600
EXPOSE 6680
EXPOSE 6681

#USER mopidy
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/bin/mopidy", "--config", "/etc/mopidy.conf:/mopidy.conf"]
